name: "Dependabot Automerge - Action"

on:
  workflow_dispatch:

jobs:
  automerge:
    name: Merge pull request
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{github.token}}
          script: |
            github.pullRequests.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })